#!/bin/sh
### BEGIN INIT INFO
# Provides: controlm
# Default-Start: 2
# Default-Stop: 0 1 3 5 6
# Description: start/stop CONTROL-M AGENT
### END INIT INFO 

case $1 in
'start') echo "Control-M-EM Agent are starting ...."
   /opt/ctm-agt/ctm/scripts/start-ag -u ctmag -p ALL
   sleep 10
   ;;
'stop') echo "Control-M-EM Agent are stopping ...."
   /opt/ctm-agt/ctm/scripts/shut-ag -u ctmag -p ALL
   sleep 10
   echo ""
   ;;
*) echo "usage : /etc/init.d/ctmagt { start | stop }"
   ;;
esac
