---
- name: download jdk from s3
  command: aws s3 cp s3://applications.dev/Talend/6.2.1/jdk-8u101-linux-x64.tar.gz /opt/
  environment: '{{ awsenv }}'
- name: unzip to /opt/
  command: tar -xzf /opt/jdk-8u101-linux-x64.tar.gz -C /opt/
- name: modify /etc/profile
  command: sed -i '$a JAVA_HOME=/opt/jdk1.8.0_101'  /etc/profile
- command: sed -i '$a PATH=$PATH:$HOME/bin:$JAVA_HOME/bin'  /etc/profile
- command: sed -i '$a JRE_HOME=/opt/jdk1.8.0_101/jre'  /etc/profile
- command: sed -i '$a PATH=$PATH:$HOME/bin:$JRE_HOME/bin'  /etc/profile
- command: sed -i '$a export JAVA_HOME' /etc/profile
- command: sed -i '$a export JRE_HOME' /etc/profile
- command: sed -i '$a export PATH' /etc/profile
- name: install to system
  command: update-alternatives --install '/usr/bin/java' 'java' '/opt/jdk1.8.0_101/jre/bin/java' 1
- command: update-alternatives --install '/usr/bin/javac' 'javac' '/opt/jdk1.8.0_101/bin/javac' 1
- command: update-alternatives --install '/usr/bin/javaws' 'javaws' '/opt/jdk1.8.0_101/jre/bin/javaws' 1
- name: set default
  command: update-alternatives --set java /opt/jdk1.8.0_101/jre/bin/java
- command: update-alternatives --set javac /opt/jdk1.8.0_101/bin/javac
- command: update-alternatives --set javaws /opt/jdk1.8.0_101/jre/bin/javaws
